version: '3'
services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: isilva100/node
    container_name: node
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 25s
    command: node index.js
    volumes:
      - ./node:/usr/src/app/node
    networks:
      - node-network
    depends_on:
      - db
    
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: isilva/nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge